# Generated by Django 5.2.7 on 2026-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lesson_description_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
